### ISSUE TITLE
8 or more parameters when declaring "ReactMethod".

### ISSUE THREAD

**Issue by ihcha** [microsoft/react-native-windows-samples#534]
Error of "CS1501" when there are 8 or more parameters when declaring "ReactMethod".
* error CS1501: No overload for method `ReadArgs' takes `8' arguments [duplicate]

it is sample... 
[ReactMethod("TestArgs")]
public void TestArgs(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, IReactPromise<int> promise)
{
    promise.Resolve(a1+a2+a3+a4+a5+a6+a7+a8);
    return;
}

OS target is UWP(Windows)

How should I solve this problem?

**Comment by ihcha** [comment]
target is UWP(windows)

**Comment by chrisglein** [comment]
Can you include the JSX snippet where you are calling this method? Or does it fail even without a callsite?

**Comment by ihcha** [comment]
> 이 문제는 환경 정보에서 도움이 될 것입니다. 이 정보를 추가하려면 문제 보고서를 수정하세요.
> 
> 최신 버전을 사용하는 경우:
> 
PS D:\Git\ReactNativeModule\example> npx react-native --version
5.0.1
PS D:\Git\ReactNativeModule\example> npx react-native run-windows --info

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 7.70 GB / 15.93 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.19.1 - C:\Program Files (x86)\nodejs\npm.CMD
  npmPackages:
    react: 17.0.1 => 17.0.2
    react-native: ^0.64.1 => 0.64.2
    react-native-windows: ^0.64.15 => 0.64.16
  Installed UWP SDKs:
    10.0.10240.0
    10.0.10586.0
    10.0.14393.0
    10.0.17763.0
    10.0.18362.0
    10.0.19041.0
> 1. `npx react-native --version`:
> 2. `npx react-native run-windows --info`:
> 
> 그렇지 않으면 `--info`존재하지 않는 경우 :
> 
> 1. `react-native -v`:
> 2. `npm ls rnpm-plugin-windows`:
> 3. `npm ls react-native-windows`:
> 4. `node -v`:
> 5. `npm -v`:
> 6. `yarn --version`:

**Comment by ihcha** [comment]
> 이 메소드를 호출하는 JSX 스니펫을 포함할 수 있습니까? 아니면 호출 사이트가 없어도 실패합니까?

This problem is just an error from 'visual studio' that creates 'ReactNative module'.
![image](https://user-images.githubusercontent.com/89837478/133006168-72100459-32a8-4d5a-af22-d3e72c3993c0.png)

**Comment by NickGerleman** [comment]
IIRC the limited parameter count for C# ReactMethods was a known limitation. 

cc @chrisglein @vmoroz

**Comment by chrisglein** [comment]
Yes, I believe there is a known limit here on args (I think the code for that is [here](https://github.com/microsoft/react-native-windows/blob/003602b90aeda1b2a43702c6a9307c0f01010e59/vnext/Microsoft.ReactNative.Managed/JSValueReader.cs#L372)). It seems reasonable that there's some limit, whether 8 is the right number or not. There is no issue that I've been able to find that's been logged on the [main repo](https://github.com/microsoft/react-native-windows/issues/new/choose) to increase that limit. At least the error for this seems relatively clear, so that's something.

Hopefully you'll able to consolidate your arguments to need less than 8? That's the immediate workaround. If that's not viable let us know why and [open an issue](https://github.com/microsoft/react-native-windows/issues/new/choose) to increase the limit.
