### ISSUE TITLE
Need documentation for how to use WinUI3 with RNW

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows-samples#93]
It will be a very long time before RNW can confidently use WinUI3 by default. In the meantime there's a manual switch to try it out. See [issue on RNW repo](https://github.com/microsoft/react-native-windows/issues/2492). We need to document those steps, and list or link to the tradeoffs, so that early adopting apps can be informed.

**Comment by asklar** [comment]
Some thoughts:
* Today, we can build a debug version of M.RN that targets WinUI 3 by setting the configuration to WinUI3 instead of Debug or Release.
* I checked in a change to the CLI and project templates that adds an option to the project linking command to use WinUI 3 - see PR #4799
* We should try to limit the probability that an app will load both WinUI 2.x and WinUI 3 as I don't think this is a [well] supported scenario

**Comment by chrisglein** [comment]
https://microsoft.github.io/react-native-windows/docs/next/winui3
